import { StyleSheet, Dimensions } from "react-native";
const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: "center",
    width: "100%",
  },
  selectedImage: {
    width: "90%",
    aspectRatio: 1,
    borderRadius: 20,
    borderColor: "#3F493A",
    borderWidth:1.2,
  },
  plant: {
    position: "absolute",
    top: 40,
    right: -200,
    width: "100%",
  },
  header: {
    marginTop: 15,
    alignItems: "center",
    backgroundColor: "#79866E",
    borderRadius: 11,
    padding:8
  },
  plantImage: {
    width: "22%",
    aspectRatio: 10/12,
    position: "absolute",
    top: 50,
    right: 15,
    borderRadius: 11,
  },
  cameraButton: {
    width: 300,
    height: 300,
    padding: 10,
    borderRadius: 150,
    backgroundColor: "#9EB98B",
    textAlign: "center",
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 4,
    borderColor: "#000",
    marginTop: 120,
  },
  galleryButton: {
    width: 100,
    height: 100,
    padding: 10,
    borderRadius: 150,
    backgroundColor: "#9EB98B",
    textAlign: "center",
    justifyContent: "center",
    alignItems: "center",
    left: 200,
    borderWidth: 4,
    borderColor: "#000",
  },
  backgroundImage: {
    position: "absolute",
    left: 0,
    top: 0,
    width: Dimensions.get("window").width,
    height: Dimensions.get("window").height,
    textAlign: "center",
    justifyContent: "center",
    alignItems: "center",
  },
  mainLogo: {
    width: "80%",
    aspectRatio: 1,
    marginRight: 10,
    textAlign: "center",
    justifyContent: "center",
  },
  galleryIcon: {
    width: "80%",
    height: "80%",
    marginRight: 0,
    borderRadius: 0,
    textAlign: "center",
    justifyContent: "center",
    position: "absolute",
  },
  location: {
    position: "absolute",
    top: 60,
    left: 30,
  },
  NavBar: {
    position: "relative",
    top: 250,
    height: 60,
    flexDirection: "row",

    backgroundColor: "white",
    width: "100%",
    alignItems: "center",
    justifyContent: "space-between",
  },
  plantsPhotos: {
    margin: 4,
    width: 120,
    height: 125,
    borderWidth:0.5,
    borderColor: "#3F493A",
    borderRadius: 15,
  },
  row: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 8,
  },
});
export default styles;
